/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mhalo.parking.service.core.domain;
@org.apache.avro.specific.AvroGenerated
public enum PaymentStatusAvroModel implements org.apache.avro.generic.GenericEnumSymbol<PaymentStatusAvroModel> {
  DEBITED, DEBIT_FAILED, REFUNDED, REFUND_FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentStatusAvroModel\",\"namespace\":\"mhalo.parking.service.core.domain\",\"symbols\":[\"DEBITED\",\"DEBIT_FAILED\",\"REFUNDED\",\"REFUND_FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
