/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mhalo.parking.service.core.domain;
@org.apache.avro.specific.AvroGenerated
public enum TransactionStatusAvroModel implements org.apache.avro.generic.GenericEnumSymbol<TransactionStatusAvroModel> {
  SUCCESS, FAILURE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransactionStatusAvroModel\",\"namespace\":\"mhalo.parking.service.core.domain\",\"symbols\":[\"SUCCESS\",\"FAILURE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
